CREATE DATABASE LEMS;

#DROP DATABASE LEMS;

USE LEMS;

CREATE TABLE Users(
	U_ID INT NOT NULL AUTO_INCREMENT,
    Email VARCHAR (100),
    Salted_Password VARCHAR(256),
    Salt VARCHAR(44) NOT NULL,
    U_Position VARCHAR (50),
    PRIMARY KEY (U_ID)
);
#SELECT * FROM Users;

#DELETE FROM USERS WHERE U_ID = 1;

#ALTER TABLE Users auto_increment = 0;

CREATE TABLE Admins (
	A_ID INT NOT NULL AUTO_INCREMENT,
    A_Name VARCHAR(50),
    A_Surname VARCHAR(50),
    A_Phone VARCHAR(50),
    A_UID INT NOT NULL,
    PRIMARY KEY (A_ID),
    FOREIGN KEY (A_UID) REFERENCES Users(U_ID) ON DELETE CASCADE
);
#SELECT * FROM Admins;

CREATE TABLE Students (
	S_ID INT NOT NULL AUTO_INCREMENT,
    S_Name VARCHAR(50),
    S_Surname VARCHAR(50),
    S_Birthdate Date,
    S_Phone VARCHAR(50),
    S_Address VARCHAR(50),
    S_GLevel INT,
    S_UID INT NOT NULL,
    PRIMARY KEY (S_ID),
    FOREIGN KEY (S_UID) REFERENCES Users(U_ID) ON DELETE CASCADE
);
#SELECT * FROM Students;

#DELETE FROM USERS WHERE U_ID = 1;

CREATE TABLE Teacher (
	T_ID INT NOT NULL AUTO_INCREMENT,
    T_Name VARCHAR(50),
    T_Surname VARCHAR(50),
    T_Birthdate Date,
    T_Phone VARCHAR(50),
    T_Address VARCHAR(50),
    T_UID INT NOT NULL,
    PRIMARY KEY (T_ID),
    FOREIGN KEY (T_UID) REFERENCES Users(U_ID) ON DELETE CASCADE
);
#SELECT * FROM Teacher;

CREATE TABLE Enrollment(
	E_ID INT NOT NULL,
    S_ID INT NOT NULL,
    T_ID INT NOT NULL,
    E_Date Date,
    PRIMARY KEY (E_ID),
    FOREIGN KEY (S_ID) REFERENCES Students(S_ID) ON DELETE CASCADE,
    FOREIGN KEY (T_ID) REFERENCES Teacher(T_ID) ON DELETE CASCADE
);
#SELECT * FROM Enrollment;

CREATE TABLE Courses(
	Course_ID INT NOT NULL,
    T_ID INT NOT NULL,
    C_Name VARCHAR(50),
    S_GLevel INT NOT NULL,
    PRIMARY KEY (Course_ID),
    FOREIGN KEY (T_ID) REFERENCES Teacher(T_ID) ON DELETE CASCADE
);
#SELECT * FROM Courses;

CREATE TABLE Grades(
	G_ID INT NOT NULL,
    S_ID INT NOT NULL,
    A_ID INT NOT NULL,
    G_Value INT,
    PRIMARY KEY (G_ID),
    FOREIGN KEY (S_ID) REFERENCES Students(S_ID) ON DELETE CASCADE
);
#SELECT * FROM Grades;

