CREATE DATABASE LEMS;

#DROP DATABASE LEMS;

USE LEMS;

CREATE TABLE Users(
	U_ID INT NOT NULL AUTO_INCREMENT,
    Email VARCHAR (100),
    Salted_password VARCHAR(256),
    Salt VARCHAR(32) NOT NULL,
    U_Position VARCHAR (50),
    PRIMARY KEY (U_ID)
);

CREATE TABLE Admins (
	A_ID INT NOT NULL,
    A_Name VARCHAR(50),
    A_Surname VARCHAR(50),
    A_Phone VARCHAR(50),
    A_UID INT NOT NULL,
    PRIMARY KEY (A_ID),
    FOREIGN KEY (A_UID) REFERENCES Users(U_ID) ON DELETE CASCADE
);

CREATE TABLE Students (
	S_ID INT NOT NULL,
    S_Name VARCHAR(50),
    S_Surname VARCHAR(50),
    S_Birthday Date,
    S_Phone VARCHAR(50),
    S_Adresa VARCHAR(50),
    S_GLevel INT,
    S_UID INT NOT NULL,
    PRIMARY KEY (S_ID),
    FOREIGN KEY (S_UID) REFERENCES Users(U_ID) ON DELETE CASCADE
);

CREATE TABLE Teacher (
	T_ID INT NOT NULL,
    T_Name VARCHAR(50),
    T_Surname VARCHAR(50),
    T_Birthday Date,
    T_Phone VARCHAR(50),
    T_Adresa VARCHAR(50),
    T_UID INT NOT NULL,
    PRIMARY KEY (T_ID),
    FOREIGN KEY (T_UID) REFERENCES Users(U_ID) ON DELETE CASCADE
);

CREATE TABLE Enrollment(
	E_ID INT NOT NULL,
    S_ID INT NOT NULL,
    T_ID INT NOT NULL,
    E_Date Date,
    PRIMARY KEY (E_ID),
    FOREIGN KEY (S_ID) REFERENCES Students(S_ID) ON DELETE CASCADE,
    FOREIGN KEY (T_ID) REFERENCES Teacher(T_ID) ON DELETE CASCADE
);

CREATE TABLE Courses(
	Course_ID INT NOT NULL,
    T_ID INT NOT NULL,
    C_Name VARCHAR(50),
    S_GLevel INT NOT NULL,
    PRIMARY KEY (Course_ID),
    FOREIGN KEY (T_ID) REFERENCES Teacher(T_ID) ON DELETE CASCADE
);

CREATE TABLE Grades(
	G_ID INT NOT NULL,
    S_ID INT NOT NULL,
    A_ID INT NOT NULL,
    G_Value INT,
    PRIMARY KEY (G_ID),
    FOREIGN KEY (S_ID) REFERENCES Students(S_ID) ON DELETE CASCADE
);

